trainingInput:
  scaleTier: CUSTOM
  region: us-east1
  masterType: n1-highmem-8
  masterConfig:
    acceleratorConfig:
      count: 1
      type: NVIDIA_TESLA_T4
  workerType: n1-highmem-8
  workerConfig:
    acceleratorConfig:
      count: 1
      type: NVIDIA_TESLA_T4
  workerCount: 5
  runtimeVersion: "2.2"
  pythonVersion: "3.7"
  
